src/Entity/Voitures.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use App\Repository\VoituresRepository;
use App\Entity\Marques;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: VoituresRepository::class)]
#[ORM\HasLifecycleCallbacks]
class Voitures
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'voitures')]
    private ?Marques $marque = null;

    #[ORM\Column(length: 120)]
    #[Assert\Length(min: 5, max: 110, minMessage: "L'introduction doit faire plus de 20 caractères", maxMessage:"L'introduction ne doit pas faire plus de 255 caractères")]
    private ?string $modele = null;

    #[ORM\Column(length: 255)]
    private ?string $slug = null;


    #[ORM\Column]
    // #[Assert\Length(min: 20, max: 110, minMessage: "L'introduction doit faire plus de 20 caractères", maxMessage:"L'introduction ne doit pas faire plus de 255 caractères")]
    private ?int $km = null;

    #[ORM\Column]
    #[Assert\NotBlank(message:"Vous devez renseigner votre ancien mot de passe")]
    private ?float $prix = null;

    #[ORM\Column]
    #[Assert\NotBlank(message:"Vous devez renseigner votre ancien mot de passe")]
    private ?float $cylindree = null;

    #[ORM\Column]
    #[Assert\NotBlank(message:"Vous devez renseigner votre ancien mot de passe")]
    private ?int $puissance = null;

    #[ORM\Column(length: 120)]
    private ?string $carburant = null;

    #[ORM\Column(length: 120)]
    private ?string $transmission = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $annee_circulation = null;

    #[ORM\Column]
    private ?int $nb_proprio = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $option_car = null;

    #[ORM\OneToMany(mappedBy: 'voitures', targetEntity: Images::class, cascade:['persist'])]
    private Collection $images;

    #[ORM\Column(length: 255)]
    private ?string $coverImg = null;

    public function __construct()
    {
        $this->images = new ArrayCollection();
    }

    #[ORM\PrePersist]
    #[ORM\PreUpdate]
    public function initializeSlug() :void
    {
        if(empty($this->slug))
        {
            $slugify = new Slugify();
            $this->slug = $slugify->slugify($this->modele.'-'.rand(2000,8000000));
        }
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMarque(): ?Marques
    {
        return $this->marque;
    }

    public function setMarque(?Marques $marque): self
    {
        $this->marque = $marque;

        return $this;
    }

    public function getModele(): ?string
    {
        return $this->modele;
    }

    public function setModele(string $modele): self
    {
        $this->modele = $modele;

        return $this;
    }
    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }
    public function getKm(): ?int
    {
        return $this->km;
    }

    public function setKm(int $km): self
    {
        $this->km = $km;

        return $this;
    }

    public function getPrix(): ?float
    {
        return $this->prix;
    }

    public function setPrix(float $prix): self
    {
        $this->prix = $prix;

        return $this;
    }

    public function getCylindree(): ?int
    {
        return $this->cylindree;
    }

    public function setCylindree(int $cylindree): self
    {
        $this->cylindree = $cylindree;

        return $this;
    }

    public function getPuissance(): ?int
    {
        return $this->puissance;
    }

    public function setPuissance(int $puissance): self
    {
        $this->puissance = $puissance;

        return $this;
    }

    public function getCarburant(): ?string
    {
        return $this->carburant;
    }

    public function setCarburant(string $carburant): self
    {
        $this->carburant = $carburant;

        return $this;
    }

    public function getTransmission(): ?string
    {
        return $this->transmission;
    }

    public function setTransmission(string $transmission): self
    {
        $this->transmission = $transmission;

        return $this;
    }

    public function getAnneeCirculation(): ?\DateTimeInterface
    {
        return $this->annee_circulation;
    }

    public function setAnneeCirculation(\DateTimeInterface $annee_circulation): self
    {
        $this->annee_circulation = $annee_circulation;

        return $this;
    }

    public function getNbProprio(): ?int
    {
        return $this->nb_proprio;
    }

    public function setNbProprio(int $nb_proprio): self
    {
        $this->nb_proprio = $nb_proprio;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getOptionCar(): ?string
    {
        return $this->option_car;
    }

    public function setOptionCar(?string $option_car): self
    {
        $this->option_car = $option_car;

        return $this;
    }

    /**
     * @return Collection<int, Images>
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Images $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images->add($image);
            $image->setVoitures($this);
        }

        return $this;
    }

    public function removeImage(Images $image): self
    {
        if ($this->images->removeElement($image)) {
            // set the owning side to null (unless already changed)
            if ($image->getVoitures() === $this) {
                $image->setVoitures(null);
            }
        }

        return $this;
    }

    public function getCoverImg(): ?string
    {
        return $this->coverImg;
    }

    public function setCoverImg(string $coverImg): self
    {
        $this->coverImg = $coverImg;

        return $this;
    }
}

src/Controller/VentesController.php
<?php

namespace App\Controller;


use App\Entity\Voitures;
use App\Form\SearchType;
use App\Form\VoituresType;
use App\Form\VoituresModifyType;
use App\Repository\ImagesRepository;
use App\Repository\VoituresRepository;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;

class VentesController extends AbstractController
{
    /**
     * Permet d'afficher les différentes voitures
     *
     * @param VoituresRepository $repo
     * @param PaginatorInterface $paginator
     * @param Request $request
     * @return Response
     */
    #[Route('/ventes', name: 'ventespage')]
    public function index(VoituresRepository $repo, PaginatorInterface $paginator, Request $request): Response
    {
        $voiture = $paginator->paginate(
            $repo->findAll(),
            $request->query->getInt('page',1),15
        );

        return $this->render('ventes/index.html.twig', [
            
            'voiture' => $voiture,
        ]);
    }
    /**
     * Ajout nouvelle voiture
     *
     * @param Request $request
     * @param EntityManagerInterface $manager
     * @return Response
     */
    #[Route("/ventes/new", name:"ventes_new")]
    #[IsGranted("ROLE_ADMIN")]
    public function create(Request $request,EntityManagerInterface $manager): Response
    {
      $voiture = new Voitures();  
      $form = $this->createForm(VoituresType::class, $voiture);
      $form->handleRequest($request);
    //   $manager->persist($voiture);
    //   $manager->flush();
       
        if($form->isSubmitted() && $form->isValid())
        {   
           // dump((string) $form->getErrors(true, false));die;
            foreach($voiture->getImages() as $image){

               $image->setVoitures($voiture);
                $manager->persist($image);
                
            }

            $file = $form['coverImg']->getData();
            if(!empty($file))
            {
                $originalFilename = pathinfo($file->getClientOriginalName(),PATHINFO_FILENAME);
                $safeFilename = transliterator_transliterate('Any-Latin;Latin-ASCII; [^A-Za-z0-9_] remove; Lower()', $originalFilename);
                $newFilename = $safeFilename."-".uniqid().".".$file->guessExtension();
                try{
                    $file->move(
                        $this->getParameter('uploads_directory'),
                        $newFilename
                    );
                }catch(FileException $e)
                {
                    return $e->getMessage();
                }
                $voiture->setCoverImg($newFilename);
            }
                // $cover->setCoverImg($voiture);
                // $manager->persist($cover);

            $manager->persist($voiture);
            $manager->flush();

            $this->addFlash(
                'success',
                "La voiture <strong>{$voiture->getModele()}</strong> a bien été enregistrée!"
            );

            return $this->redirectToRoute('ventes_show', [
                'slug' => $voiture->getSlug()
            ]);
        }
       
    return $this->renderForm('ventes/new.html.twig', [
        // 'hasError'=>$error !== null,
        
        'form' => $form
        
        
        
    ]);
    }
    /**
     * Permet de faire une recherche par mot clés
     *
     * @param Request $request
     * @param VoituresRepository $repov
     * @return void

    #[Route('/ventes', name: 'ventespagesearch')]
    public function search(Request $request,VoituresRepository $repov)
    {
        $form = $this->createForm(SearchType::class);
        $search = $form->handleRequest($request);

        return $this->render('/ventes/index.html.twig',[
            'formsearch'=>$form->createView()
        ]);
    }
     **/


    /**
     * Modification annonces
     */
    #[Route("/ventes/{slug}/edit", name:'voiture_edit')]
    #[Security("is_granted('ROLE_ADMIN')", message:"Cette annonce ne vous appartient pas, vous ne pouvez pas la modifier")]
    public function edit(Request $request, EntityManagerInterface $manager, Voitures $voitures):Response
    {
        $fileName = $voitures->getCoverImg();
        if(!empty($fileName))
        {
            new File($this->getParameter('uploads_directory').'/'.$voitures->getCoverImg());
        }

        $form = $this->createForm(VoituresModifyType::class, $voitures);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid())
        {           
                $voitures->setCoverImg($fileName);

                $voitures->setSlug('');
                $manager->persist($voitures);
                $manager->flush();

                $this->addFlash(
                    'success',
                    "L'annonce <strong>{$voitures->getModele()}</strong> a bien été modifiée"
                );

                return $this->redirectToRoute('ventes_show',['slug'=>$voitures->getSlug()]);
        }


        return $this->renderForm("ventes/edit.html.twig",[
            
            "form" => $form,
            "voitures"=>$voitures
        ]);
    }
    /**
     * Permet d'afficher une voiture
     */
    #[Route('/ventes/{slug}', name:'ventes_show')]
    public function show(string $slug, Voitures $voiture,ImagesRepository $images):Response
    {
       $img = $images->findAll();
       

        return $this->render('ventes/show.html.twig',[
            'voiture' => $voiture,
            'images'=> $img
            
        ]);
    }
}

templates/ventes/_collection.html.twig
{% block _voitures_images_widget %}
    <p>Ici, vous pouvez ajouter vos propres images</p>
    {{form_widget(form)}}
    <input type="hidden" id="widgets-counter" value="0">
    <div class="form-group">
        <button type="button" id="add_image" class="btn btn-primary">Ajouter une image</button>
    </div>
{% endblock %}

{% block _voitures_images_entry_row %}
{# entry précie le entry_type de notre annonceType au niveau de la collection - donc chaque formulaire de ImageType #}
    {{form_widget(form)}}
    {# cela m'a permis de juste afficher le widget et plus les label __name__ (0,1,2,3,...) #}
{% endblock %}

{% block _voitures_images_entry_widget %}
    <div class="form-group my-2" id="block_{{id}}">
        <div class="row">
            <div class="col-10">
                <div class="row">
                    <div class="col">
                        {{form_widget(form.linkImg)}}
                        {{form_errors(form.linkImg)}}
                    </div>
                    
                </div>
            </div>
            <div class="col-2">
                <button type="button" class="btn btn-danger" data-action="delete" data-target="#block_{{id}}">X</button>
            </div>
        </div>
    </div>
    

    
{% endblock %}

templates/ventes/_vente.html.twig
{% set url = path("ventes_show",{'slug':voiture.slug}) %}
<div class="col-md-4 bg-white mt-5 mb-5 ">
                <div class="card card-car bg-white  mb-3">
                    <div class="card-header bg-white text-center">
                   
                        
                        <h3>{{voiture.Marque.nom}}</h3>
                            
                    
                        
                    </div>
                    <img src="images/coverimg/{{voiture.coverImg}}" class="rounded mx-auto d-block bg-white" width="350" height="200" alt="Image de l'voiture" class="starsimg">
                    <div class="card-body bg-white">
                        <div class="card-title text-center bg-white">
                            modele : <h4>{{voiture.modele}}</h4>
                        </div>
                        <p class="card-tex bg-white ">
                            <p>-</strong>{{voiture.km}} km</p>
                            <p>-Puissance : {{voiture.puissance}} CH</p>
                            <p>-Carburant : {{voiture.carburant}}</p>
                            <p>-Année : {{voiture.anneeCirculation | date('d/m/Y')}}</p>
                            <p>-Prix : {{voiture.prix}} €</p>
                        </p>
                        <div class="text-center">
                        <a href="{{url}}" class="btn btn-secondary">Découvrir la voiture</a>
                        </div>
                    </div>
                </div>

templates/ventes/edit.html.twig
{% extends "base.html.twig" %}

{% block title %}Modification de l'annonce : {{voitures.modele}}{% endblock %}

{# {% form_theme myform 'bootstrap_5_layout.html.twig' %} #}
{% form_theme form 'ventes/_collection.html.twig' %}

{% block body %}
    <div class="container">
        <h1>Modification de l'annonce : {{voitures.modele}}</h1>
        {{form_start(form)}}
            <div class="container">
                <div>
                    {{form_widget(form)}}
                </div>
            </div>
            <button type="submit" class="btn btn-warning mt-3">Modifier</button>
        {{form_end(form)}}
    </div>
{% endblock %}

{% block javascripts %}
   {# {{encore_entry_script_tags('annonce')}} #}
{% endblock %}

templates/ventes/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ventes{% endblock %}

{% block body %}
<div class="container-fluid col-8 mt-5">
  {# {{form((formsearch))}} #}
     <div class="main">
  <h1 class="main-heading">
    
    <span class="main-heading-tercary">Nos ventes  </span>
  </h1>
</div>


    
    {# for marque #}
    <div class="row">
   
        
    
    {% for voiture in voiture %}

        {% include "ventes/_vente.html.twig" %}
            
            </div> 
    {% endfor %}
        <div class="navigation d-flex justify-content-center">
        </div>
 
            {{knp_pagination_render(voiture)}}
     
    
    </div>
    
        


        
</div>            

{% endblock %}

templates/ventes/new.html.twig
{% extends "base.html.twig" %}

{% block title %}Création d'une voiture{% endblock %}
{% form_theme form 'ventes/_collection.html.twig' %}

{% block body %}
    <div class="container">
        <h1 class="mt-5 mb-5">Création d'une nouvelle voiture</h1>
        {{form_start(form)}}
            <div class="container">
                <div>
                    {{form_widget(form)}}
                        
                </div>
            </div>
            <button type="submit" class="btn btn-primary mt-3">Création d'une voiture</button>
            
        {{form_end(form)}}
    </div>

     
{% endblock %}
{% block javascripts %}
{# {{ encore_entry_script_tags('app') }} #}
    <script >
        
    console.log('hello')
    const addImage = document.querySelector('#add_image')

    addImage.addEventListener('click',()=>{
    // compter combien j'ai de form-group pour les indices ex: annonce_image_0_url
    console.log('bisous')
    const widgetCounter = document.querySelector("#widgets-counter")
    const index = +widgetCounter.value // le + permet de transofmer en nombre, value rends tjrs un string 
    const annonceImages = document.querySelector('#voitures_images')

    //recup le prototype des entrées data-prototype
    const prototype = annonceImages.dataset.prototype.replace(/__name__/g, index) // drapeau g pour indiquer que l'on va le faire plusieurs fois 

    //injecter le code dans la div
    annonceImages.insertAdjacentHTML('beforeend', prototype)
    widgetCounter.value = index+1

    handleDeleteButtons() // pour mettre à jour le tablea deletes et ajouter l'évent 
})

const updateCounter = () => {
    const count = document.querySelectorAll('#voitures_images div.form-group').length
    document.querySelector('#widgets-counter').value = count
}

const handleDeleteButtons = () => {
    var deletes = document.querySelectorAll("button[data-action='delete']")

    deletes.forEach(button => {
        button.addEventListener('click',()=>{
            const target = button.dataset.target
            const elementTarget = document.querySelector(target)
            if(elementTarget){
                elementTarget.remove() // supprimer l'élément 
            }
        })
    })


}

updateCounter()
handleDeleteButtons()

    </script>
{% endblock %}

templates/ventes/show.html.twig
{% extends 'base.html.twig' %}
{% block body %}

    <div class="container-fluid  col-10 text-center">
        <div class="card mb-3 text-center">
  <div class="card-body ">
    
    <div class="intro">
        <ul class="list-group list-group-flush">
        <li class="list-group-item">{{voiture.Marque.nom}} {{voiture.modele}}</li>
        <li class="list-group-item">{{voiture.prix}} €</li>
        </ul>

                <img src="../images/coverimg/{{voiture.coverImg}}" class="" width="40%" height="400" alt="">
            
  </div>  
            </div>  
        </div>
          
     
        <div class="galcontain">
  <ul class="list-group list-group-flush">
    
    <li class="list-group-item">Kilomètrage: {{voiture.km}} km</li>
    <li class="list-group-item">Cylindrée : {{voiture.cylindree}} l</li>
    <li class="list-group-item">Puissance : {{voiture.puissance}} Ch</li>
    <li class="list-group-item">Carburant : {{voiture.carburant}}</li>
    <li class="list-group-item">Transmission: {{voiture.transmission}}</li>
    <li class="list-group-item">Date de mise en Circulation: {{voiture.anneeCirculation | date('d/m/Y')}}</li>
    <li class="list-group-item">Nombre de propriétaires: {{voiture.nbProprio}}</li>
    <li class="list-group-item">Description : {{voiture.description}}</li>
    <li class="list-group-item">Options : {{voiture.optionCar}}</li>
    
  </ul>
  <div class="container  " id="galerie">
        <div class="row galimg ">
            <div class="rounded mx-auto d-block  col-md-8 mb-3">

                <div class="bd-example">
                    <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="false">
                        <div class="carousel-indicators">
                         {% for images in voiture.Images %}
                            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="{{loop.index0}}" {% if loop.first %} class="active" aria-current="true" {% endif %} aria-label="Slide {{loop.index}}"></button>
                        {% endfor %} 
                           
                        </div>
                        <div class="carousel-inner">
                            {% for images in voiture.images %}
                                <div class="carousel-item {% if loop.first %}active{% endif %}">
                                    <img src="{{images.linkImg}}" class="d-block w-100" alt="image de {{voiture.modele}}">
                                    <div class="carousel-caption d-none d-md-block">
                                         <h5>{{voiture.modele}}</h5>
                                        
                                    </div>
                                </div>
                            {% endfor %}
                           
                        </div>
                        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                            <span class="visually-hidden">Previous</span>
                        </button>
                        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                            <span class="visually-hidden">Next</span>
                        </button>
                    </div>
                </div>

            </div>
            </div>
            </div>
            </div>
  
  <div class="card-footer text-muted">
    {{random(1,20)}} days ago
  </div>
</div>
<div class="card text-center">
  <div class="card-body">
    <a href="{{path('ventespage')}}" class="card-link">Retourner à nos ventes</a>
    <a href="{{path('homepage')}}" class="card-link">Retour à l'accueil</a>
  </div>
  {% if is_granted('ROLE_ADMIN') %}
                <a href="{{path('voiture_edit',{'slug': voiture.slug})}}" class="btn btn-warning mx-2">Modification de l'annonce</a>
                {# <a href="{{path('ads_delete',{'slug': ad.slug})}}" class="btn btn-danger mx-2">Supprimer l'annonce</a> #}
            {% endif %}
</div>
    </div>

{% block javascripts %}

    <script>
        console.log('test enfant')
        $('.product-img--main')
        // tile mouse actions
        .on('mouseover', function(){
          $(this).children('.product-img--main__image').css({'transform': 'scale('+ $(this).attr('data-scale') +')'});
        })
        .on('mouseout', function(){
          $(this).children('.product-img--main__image').css({'transform': 'scale(1)'});
        })
        .on('mousemove', function(e){
          $(this).children('.product-img--main__image').css({'transform-origin': ((e.pageX - $(this).offset().left) / $(this).width()) * 100 + '% ' + ((e.pageY - $(this).offset().top) / $(this).height()) * 100 +'%'});
        })
        // tiles set up
        .each(function(){
          $(this)
            // add a image container
            .append('<div class="product-img--main__image"></div>')
            // set up a background image for each tile based on data-image attribute
            .children('.product-img--main__image').css({'background-image': 'url('+ $(this).attr('data-image') +')'});
        });
    </script>
{% endblock %}
{% endblock %}